# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50, unique=True)),
                ('shopAddress', models.CharField(max_length=50)),
                ('shopCover', models.ImageField(blank=True, null=True, upload_to='coverImg')),
            ],
        ),
        migrations.CreateModel(
            name='shopPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopPic', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ShopInfo')),
            ],
        ),
        migrations.CreateModel(
            name='shoptag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20, unique=True)),
                ('tagPic', models.ImageField(blank=True, null=True, upload_to='tagImg')),
                ('tagIntro', models.CharField(default='None', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10, null=True)),
                ('level', models.IntegerField(choices=[(1, 'owner'), (2, 'manager'), (3, 'user')], default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shoptag'),
        ),
    ]
