# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50, unique=True)),
                ('shopAddress', models.CharField(max_length=50)),
                ('shopCover', models.ImageField(blank=True, null=True, upload_to='cover')),
                ('shopPic', models.ImageField(blank=True, null=True, upload_to='picture')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10, null=True),
        ),
    ]
